version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend 
    ports:
      - "5000:5000"
    volumes:
      - ./database/ragas_test_database.db:/database/ragas_test_database.db
    networks:
      - app-network

networks:
  app-network: 
    driver: bridge