"""empty message

Revision ID: 74ba7a6c3636
Revises: 
Create Date: 2024-05-12 00:35:13.131663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ba7a6c3636'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_type', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('ground_truth', sa.Text(), nullable=True),
    sa.Column('faithfulness', sa.Integer(), nullable=True),
    sa.Column('answer_relevancy', sa.Integer(), nullable=True),
    sa.Column('context_recall', sa.Integer(), nullable=True),
    sa.Column('context_precision', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contexts')
    op.drop_table('questions')
    # ### end Alembic commands ###
