"""empty message

Revision ID: f5d09810de55
Revises: 74ba7a6c3636
Create Date: 2024-05-12 20:06:47.782044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d09810de55'
down_revision = '74ba7a6c3636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('top_n_documents', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('strictness', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('temperature', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('presence_penalty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('frequence_penalty', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('frequence_penalty')
        batch_op.drop_column('presence_penalty')
        batch_op.drop_column('temperature')
        batch_op.drop_column('strictness')
        batch_op.drop_column('top_n_documents')

    # ### end Alembic commands ###
